spring.main.allow-bean-definition-overriding: true

operations:
  interval: 1000

sensor:
  distance:
    pin: 0
  motion:
    pin: 1
  sound:
    pin: 2
    interval: 1000

motion:
  track:
    right:
      forward:
        pin: 3
      backward:
        pin: 4
    left:
      forward:
        pin: 5
      backward:
        pin: 6
